### ISSUE TITLE
HDR Status failed

### ISSUE THREAD

**Issue by Freeride1986** [volkerrichert/ioBroker.oppoplayer#13]
The HDR status is not read out regularly. 
IoBroker shows SDR permanently, although the Oppo Player shows HDR in the display.
In my opinion, the status is simply not updated and is therefore stuck in SDR mode.

**Comment by volkerrichert** [comment]
Hm. The FW allways returns "SDR". Even if a UHBD is playing.

```
oppoplayer.0 | 2020-02-09 15:02:50.838 | debug | (16875) <== @QHS OK SDR
-- | -- | -- | --
oppoplayer.0 | 2020-02-09 15:02:50.838 | silly | (16875) <== @QHS OK SDR
oppoplayer.0 | 2020-02-09 15:02:50.837 | debug | (16875) ==> #QHS
oppoplayer.0 | 2020-02-09 15:02:50.836 | silly | (16875) === QHS
oppoplayer.0 | 2020-02-09 15:02:45.731 | debug | (16875) <== @QHS OK SDR
oppoplayer.0 | 2020-02-09 15:02:45.730 | silly | (16875) <== @QHS OK SDR
oppoplayer.0 | 2020-02-09 15:02:45.729 | debug | (16875) ==> #QHS
oppoplayer.0 | 2020-02-09 15:02:45.729 | silly | (16875) === QHS
oppoplayer.0 | 2020-02-09 15:02:40.626 | debug | (16875) <== @QHS OK SDR
oppoplayer.0 | 2020-02-09 15:02:40.625 | silly | (16875) <== @QHS OK SDR
```

And it isn't report any changes itself. I try to poll teh value. Sorry. But there is a mistake. It will write it's "SDR" into "hdr" instead of hdrStatus.

**Comment by volkerrichert** [comment]
ahh, that's wrong... one is settings.hdr the other ons is status.hdr..

**Comment by volkerrichert** [comment]
Maybe ist allways SDR becaus my beamer was off... I'll retest it

**Comment by volkerrichert** [comment]
Can you test the master branch (or add the poll-flag to your installation)? i can't test it, bacuase i haven't any HDR output device

**Comment by Freeride1986** [comment]
I have tested it. 
I can see the HDR state on oppoplayer.0.status - but i can't trigger with it. (Switching from SDR to HDR works perfect)
But when I push the HDR Button on the Oppo App the status is switching on oppoplayer.0.settings >> hdr on - i can trigger on it but not on HDR State.

![HDR Setting On](https://user-images.githubusercontent.com/16300603/74725127-bfa58580-523d-11ea-9dd6-faa57738b85e.JPG)
![HDR Status](https://user-images.githubusercontent.com/16300603/74725128-c03e1c00-523d-11ea-90ff-86d224542c24.JPG)

**Comment by volkerrichert** [comment]
Ok, poll the HDR status seems to work. fine. I'll dig into the settings. May I ask you to check a fix later on?

**Comment by Freeride1986** [comment]
Of course, if you can fix it - i will test it tommorow. But how can it be that the readings have the right value but you cannot respond to them?

**Comment by volkerrichert** [comment]
ah, ok. I'll try

**Comment by Freeride1986** [comment]
Hello Volker, do you have some news for us?

**Comment by volkerrichert** [comment]
Yeap, some....

- The Oppo documentation sucks :-(
- Setting "Auto" / "On" works as documented
- "Off" not. I think because of "Off BT709" & "Off BT2020", shown in the app
- "StripMetadata" & "Dolby Vison" doesn't work as well.
- I didn't find the matching command by testing or looking in the FW, yet.
- no, "#SHR StripMetadata" doesn't work, even if "StripMetadata" is a valid setting

But I found a very simple JSON-Rest API on port 436 by sniffing the app traffic. You can setup a ton more with this API. But I haven't see something like e.g. "nits" in the RS232 / IP protocol.

So, I don't know if it's useful to implement all the other stuff using a second interface. I'll maybe add a setter for all HDR-Settings, but all the other stuff... 

Do you think they are useful?

**Comment by volkerrichert** [comment]
but, hdr setting is updated if you change it in the app

**Comment by Freeride1986** [comment]
Thanks for your work, i thing it's not required to add more states - all required readings are visible.
the only thing that comes to mind is reading out the number of nits to react to a preset. But the new JVC Projector are react on the Frame in the Movie. So i don't need it =)

**Comment by volkerrichert** [comment]
Maybe I add switching hdr setting... I have to check the API Workflow. I saw some login and out.
